file(STRINGS "${CMAKE_SOURCE_DIR}/VERSION" OPENTEXTURE_VERSION_LINE LIMIT_COUNT 1)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/VERSION")
string(REGEX REPLACE "\r" "" OPENTEXTURE_VERSION_LINE "${OPENTEXTURE_VERSION_LINE}")
string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+" OPENTEXTURE_TRIPLET "${OPENTEXTURE_VERSION_LINE}")
if(NOT OPENTEXTURE_TRIPLET)
  message(FATAL_ERROR "VERSION first line must start with major.minor.patch")
endif()

string(LENGTH "${OPENTEXTURE_TRIPLET}" _ot_tlen)
string(SUBSTRING "${OPENTEXTURE_VERSION_LINE}" "${_ot_tlen}" -1 _ot_rest)
string(STRIP "${_ot_rest}" OPENTEXTURE_VERSION_SUFFIX)
if(OPENTEXTURE_VERSION_SUFFIX STREQUAL "")
  set(OPENTEXTURE_PLUGIN_VERSION_STR "${OPENTEXTURE_TRIPLET}")
else()
  set(OPENTEXTURE_PLUGIN_VERSION_STR "${OPENTEXTURE_TRIPLET} ${OPENTEXTURE_VERSION_SUFFIX}")
endif()

string(REPLACE "." ";" _ot_ver_parts "${OPENTEXTURE_TRIPLET}")
list(GET _ot_ver_parts 0 OPENTEXTURE_VER_MAJOR)
list(GET _ot_ver_parts 1 OPENTEXTURE_VER_MINOR)
list(GET _ot_ver_parts 2 OPENTEXTURE_VER_PATCH)

set(OPENTEXTURE_PLUGIN_DISPLAY "${OPENTEXTURE_TRIPLET}")
set(OPENTEXTURE_OFX_IDENTIFIER "com.LSP.OpenTexture.${OPENTEXTURE_TRIPLET}")
set(OPENTEXTURE_OFX_BUNDLE_STEM "LSP_Open_Texture_${OPENTEXTURE_PLUGIN_DISPLAY}")
set(OPENTEXTURE_OFX_EXECUTABLE_NAME "${OPENTEXTURE_OFX_BUNDLE_STEM}.ofx")
set(OPENTEXTURE_PLUGIN_ICON_NAME "com.LSP.OpenTexture.${OPENTEXTURE_PLUGIN_DISPLAY}.png")
set(OPENTEXTURE_RELEASE_FOLDER_MACOS "${OPENTEXTURE_OFX_BUNDLE_STEM}_macos")
set(OPENTEXTURE_RELEASE_FOLDER_WINDOWS "${OPENTEXTURE_OFX_BUNDLE_STEM}_windows")

set(OPENTEXTURE_VERSION_GEN "${CMAKE_SOURCE_DIR}/plugin/version_gen.h")

configure_file(
  "${CMAKE_SOURCE_DIR}/cmake/version_gen.h.in"
  "${OPENTEXTURE_VERSION_GEN}"
  @ONLY
)

set(PLUGIN_NUMERIC_VERSION "${OPENTEXTURE_TRIPLET}")
set(PLUGIN_DISPLAY_VERSION "${OPENTEXTURE_PLUGIN_VERSION_STR}")
set(OFX_EXECUTABLE_NAME "${OPENTEXTURE_OFX_EXECUTABLE_NAME}")
set(PLUGIN_OFX_IDENTIFIER "${OPENTEXTURE_OFX_IDENTIFIER}")

add_custom_target(opentexture_gen_version ALL DEPENDS "${OPENTEXTURE_VERSION_GEN}")
